#!/usr/bin/env python3
"""
Sprint 3 Phase 3A — CLIENTS backfill generator.

Reads the CLIENTS array on line 3667 of index.html, emits
tools/backfill_clients.sql containing a single CTE statement that:
  1. Inserts the "Manna Maids" business row.
  2. Inserts all 329 client rows, business_id joined from the CTE.

Decisions baked in (see Sprint 3 audit):
  - margin:  dropped. Column left NULL; regenerated from jobs later.
  - freq:    dropped. UI derives label from frequency enum.
  - fc:      "RMS - EOW" -> "RMS-EOW", cast to frequency_code enum.
  - zone:    pass-through text. Empty -> NULL.
  - dates:   MM/DD/YYYY -> DATE 'YYYY-MM-DD'. Empty -> NULL.
  - text:    empty string -> NULL for em, pkg, zone, notes.
  - ids:     legacy numeric id lands in external_id; DB id is uuid_generate_v4().

Output is NOT committed (see .gitignore — contains client PII).
Re-run this script to regenerate deterministically.
"""
import json
import re
import datetime
import pathlib
from collections import Counter

INDEX_HTML = pathlib.Path("/Users/myhelper/cleaningapp/index.html")
OUT = pathlib.Path("/Users/myhelper/cleaningapp/tools/backfill_clients.sql")
BIZ_NAME = "Manna Maids"
BIZ_EMAIL = "captainclean115@gmail.com"
EXPECTED_COUNT = 329


def sql_str(s):
    if s is None or s == "":
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def sql_date(s):
    if not s:
        return "NULL"
    d = datetime.datetime.strptime(s, "%m/%d/%Y").date()
    return f"DATE '{d.isoformat()}'"


def sql_freq(fc):
    code = re.sub(r" *- *", "-", fc)
    return f"'{code}'::frequency_code"


def sql_num(n):
    return repr(float(n))


def load_clients():
    with INDEX_HTML.open() as f:
        for i, line in enumerate(f, 1):
            if i == 3667:
                raw = line
                break
    m = re.search(r"const CLIENTS = (\[.*\]);", raw)
    if not m:
        raise SystemExit("CLIENTS literal not found on line 3667")
    arr = json.loads(m.group(1))
    if len(arr) != EXPECTED_COUNT:
        raise SystemExit(f"expected {EXPECTED_COUNT} clients, got {len(arr)}")
    return arr


def generate_sql(arr):
    cols = [
        "business_id", "external_id", "first_name", "last_name",
        "address", "city", "zip_code", "zone", "phone", "email",
        "frequency", "last_service_date", "next_service_date",
        "balance", "package", "notes",
    ]
    value_cols = cols[1:]  # business_id comes from CTE join, not VALUES

    rows = []
    for e in arr:
        rows.append("  (" + ", ".join([
            sql_str(e["id"]),
            sql_str(e["fn"]),
            sql_str(e["ln"]),
            sql_str(e["addr"]),
            sql_str(e["city"]),
            sql_str(e["zip"]),
            sql_str(e["zone"]),
            sql_str(e["ph"]),
            sql_str(e["em"]),
            sql_freq(e["fc"]),
            sql_date(e["last"]),
            sql_date(e["next"]),
            sql_num(e["bal"]),
            sql_str(e["pkg"]),
            sql_str(e["notes"]),
        ]) + ")")

    parts = []
    parts.append("-- Sprint 3 Phase 3A client backfill — generated by tools/backfill_clients.py")
    parts.append(f"-- Rows: {len(arr)}   Business: {BIZ_NAME} / {BIZ_EMAIL}")
    parts.append("-- DO NOT COMMIT (contains client PII)")
    parts.append("")
    parts.append("WITH new_biz AS (")
    parts.append(f"  INSERT INTO public.businesses (name, owner_email)")
    parts.append(f"  VALUES ({sql_str(BIZ_NAME)}, {sql_str(BIZ_EMAIL)})")
    parts.append("  RETURNING id")
    parts.append("),")
    parts.append("inserted AS (")
    parts.append(f"  INSERT INTO public.clients (")
    parts.append("    " + ", ".join(cols))
    parts.append("  )")
    parts.append("  SELECT new_biz.id, v.*")
    parts.append("  FROM new_biz, (VALUES")
    parts.append(",\n".join(rows))
    parts.append(f"  ) AS v({', '.join(value_cols)})")
    parts.append("  RETURNING id")
    parts.append(")")
    parts.append("SELECT")
    parts.append("  (SELECT id FROM new_biz)        AS business_id,")
    parts.append("  (SELECT COUNT(*) FROM inserted) AS client_rows_inserted;")
    parts.append("")
    return "\n".join(parts)


def print_expected(arr):
    print("=== expected post-write verification values ===")
    print(f"total rows: {len(arr)}")
    freq_counts = Counter(re.sub(r" *- *", "-", e["fc"]) for e in arr)
    print("frequency distribution:")
    for k in sorted(freq_counts):
        print(f"  {k}: {freq_counts[k]}")
    for label, pred in [
        ("email   null", lambda e: not e["em"]),
        ("package null", lambda e: not e["pkg"]),
        ("zone    null", lambda e: not e["zone"]),
        ("notes   null", lambda e: not e["notes"]),
        ("last    null", lambda e: not e["last"]),
        ("next    null", lambda e: not e["next"]),
    ]:
        print(f"  {label}: {sum(1 for e in arr if pred(e))}")
    bals = [e["bal"] for e in arr]
    print(f"balance: min={min(bals)} max={max(bals)} negatives={sum(1 for b in bals if b<0)}")


def main():
    arr = load_clients()
    sql = generate_sql(arr)
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(sql)
    print(f"wrote {OUT}  ({len(sql)} chars, {sql.count(chr(10))} lines)")
    print_expected(arr)


if __name__ == "__main__":
    main()
